-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                         --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

------------------
---- MONITORS ----
------------------
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---------------------
---- MY PROGRAMS ----
---------------------
local terminal = "foot"
local fileManager = "dolphin"
local menu        = "hyprlauncher"

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function () 
  --hl.exec_cmd("hyprpaper")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    general = {
        gaps_in  = -2,
        gaps_out = -2,
        gaps_workspaces = 100,
        border_size = 4,
        
        ["col.active_border"] = "#ef934d",
        ["col.inactive_border"] = "#0f0f0f", 
    },
    
    ["animations.enabled"] = false,
    ["decoration.shadow.enabled"] = false,
    ["decoration.blur.enabled"] = false,
    dwindle = { preserve_split = true },
    master = { new_status = "master" },
    scrolling = { fullscreen_on_one_column = true },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = "#0f0f0f",
    },
})

---------------
---- INPUT ----
---------------
hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = { natural_scroll = false },
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------
local mainMod = "SUPER"
local confMod = "ALT"


hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + CTRL + D", hl.dsp.exec_cmd("discord"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("steam"))
hl.bind(mainMod .. " + CTRL + G", hl.dsp.exec_cmd("geogebra"))

hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("code"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("librewolf"))



function librewolf_flag()
	if hl.get_active_window() == nil then
		return "--new-window"
	end
    local window = hl.get_active_window().class:lower()
    if window == "librewolf" then
        return "--new-tab"
    end
    return "--new-window"
end

hl.bind(mainMod .. " + A", function()		  hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://wiki.archlinux.org/title/Main_page")) end)
hl.bind(mainMod .. " + SHIFT + A", function() hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://aternos.org/servers/")) end)
hl.bind(mainMod .. " + D", function()   hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://www.desmos.com/calculator")) end)
hl.bind(mainMod .. " + E", function()   hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://www.larousse.fr/")) end)
hl.bind(mainMod .. " + G", function()  		  hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://mail.google.com/mail/u/0/?hl=fr#inbox")) end)
hl.bind(mainMod .. " + SHIFT + G", function() hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://gemini.google.com/app")) end)
hl.bind(mainMod .. " + CTRL + SHIFT + G", function() hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://www.geogebra.org/classic")) end)
hl.bind(mainMod .. " + L", function()   	  hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://mon.lyceeconnecte.fr/timeline/timeline")) end)
hl.bind(mainMod .. " + T", function()   	  hl.dispatch(hl.dsp.exec_cmd("librewolf " .. librewolf_flag() .." https://aternos.org/servers/")) end)

hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("prismlauncher"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("prismlauncher -l modern"))
hl.bind(mainMod .. " + Comma", hl.dsp.exec_cmd("prismlauncher -l ars-nouveau"))

hl.bind(mainMod .. " + " .. confMod .. " + F", hl.dsp.exec_cmd("foot micro ~/.config/foot/foot.ini"))
hl.bind(mainMod .. " + " .. confMod .. " + D", hl.dsp.exec_cmd("foot micro ~/.config/dunst/dunstrc"))
hl.bind(mainMod .. " + " .. confMod .. " + H", hl.dsp.exec_cmd("foot micro ~/.config/hypr/hyprland.lua"))
hl.bind(mainMod .. " + " .. confMod .. " + P", hl.dsp.exec_cmd("foot micro ~/.config/hypr/hyprpaper.conf"))

hl.bind(mainMod .. " + Backspace", hl.dsp.window.close("pkill"))
hl.bind(mainMod .. " + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + up", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + CTRL + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.focus({ direction = "down" }))

for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,                hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,        hl.dsp.window.move({ workspace = i, follow = false}))
    hl.bind(mainMod .. " + CTRL + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Screenshots (Hyprshot)
local dir = "/home/beglary/screenshots/"
local date_format = "$(date +%d-%m-%y_%H-%M-%S).png"

hl.bind("Print", hl.dsp.exec_cmd("sh -c 'mkdir -p " .. dir .. " && hyprshot -m output -d " .. dir .. " -f " .. date_format .. "'"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("sh -c 'mkdir -p " .. dir .. " && hyprshot -m window -d " .. dir .. " -f " .. date_format .. "'"))
hl.bind("CONTROL + Print", hl.dsp.exec_cmd("sh -c 'mkdir -p " .. dir .. " && hyprshot -m region -d " .. dir .. " -f " .. date_format .. "'"))

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})
